<a href="https://colab.research.google.com/github/iamsonia9/iamsonia9/blob/main/Numpy_task_2.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Numpy



#### 1. Import the numpy package under the name `np` (★☆☆) 
(**hint**: import … as …)

In [4]:
import numpy as np

#### 2. Print the numpy version and the configuration (★☆☆) 
(**hint**: np.\_\_version\_\_, np.show\_config)

In [ ]:
np.__version__
np.show_config()

'1.21.6'

#### 3. Create a null vector of size 10 (★☆☆) 
(**hint**: np.zeros)

In [ ]:
x = np.zeros(10)
print(x)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


#### 4.  How to find the memory size of any array (★☆☆) 
(**hint**: size, itemsize)

In [ ]:
n = np.zeros((4,4))
print("%d bytes" %(n.size*n.itemsize))

128 bytes


#### 5.  How to get the documentation of the numpy add function from the command line? (★☆☆) 
(**hint**: np.info)

In [ ]:
print(np.info(np.add))

add(x1, x2, /, out=None, *, where=True, casting='same_kind', order='K', dtype=None, subok=True[, signature, extobj])

Add arguments element-wise.

Parameters
----------
x1, x2 : array_like
    The arrays to be added.
    If ``x1.shape != x2.shape``, they must be broadcastable to a common
    shape (which becomes the shape of the output).
out : ndarray, None, or tuple of ndarray and None, optional
    A location into which the result is stored. If provided, it must have
    a shape that the inputs broadcast to. If not provided or None,
    a freshly-allocated array is returned. A tuple (possible only as a
    keyword argument) must have length equal to the number of outputs.
where : array_like, optional
    This condition is broadcast over the input. At locations where the
    condition is True, the `out` array will be set to the ufunc result.
    Elsewhere, the `out` array will retain its original value.
    Note that if an uninitialized `out` array is created via the default
    ``out

#### 6.  Create a null vector of size 10 but the fifth value which is 1 (★☆☆) 
(**hint**: array\[4\])

In [ ]:
x = np.zeros(10)
x[4]=1
print(x)

[0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]


#### 7.  Create a vector with values ranging from 10 to 49 (★☆☆) 
(**hint**: np.arange)

In [ ]:
v = np.arange(10,50)
print(v)

[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49]


#### 8.  Reverse a vector (first element becomes last) (★☆☆) 
(**hint**: array\[::-1\])

In [ ]:
x = np.arange(10,40)
x = x[::-1]
print(x)


[39 38 37 36 35 34 33 32 31 30 29 28 27 26 25 24 23 22 21 20 19 18 17 16
 15 14 13 12 11 10]


#### 9.  Create a 3x3 matrix with values ranging from 0 to 8 (★☆☆) 
(**hint**: reshape)

In [ ]:
x = np.arange(9).reshape(3,3)
print(x)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


#### 10. Find indices of non-zero elements from \[1,2,0,0,4,0\] (★☆☆) 
(**hint**: np.nonzero)

In [ ]:
n = np.nonzero([1,2,0,0,4,0])
print(n)

(array([0, 1, 4]),)


#### 11. Create a 3x3 identity matrix (★☆☆) 
(**hint**: np.eye)

In [ ]:
z = np.eye(3)
print(z)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


#### 12. Create a 3x3x3 array with random values (★☆☆) 
(**hint**: np.random.random)

In [ ]:
x = np.random.random((3,3,3))
x

array([[[0.9402163 , 0.9684068 , 0.7876507 ],
        [0.13400738, 0.94172415, 0.32781373],
        [0.85348471, 0.47456335, 0.60758684]],

       [[0.58948688, 0.07029197, 0.0215811 ],
        [0.14724454, 0.50844538, 0.07925641],
        [0.26136398, 0.95158826, 0.14796886]],

       [[0.75052016, 0.77554216, 0.2361165 ],
        [0.82364727, 0.09433654, 0.4209852 ],
        [0.21315173, 0.52527289, 0.95677215]]])

#### 13. Create a 10x10 array with random values and find the minimum and maximum values (★☆☆) 
(**hint**: min, max)

In [ ]:
x = np.random.random((10,10))
print(x)
xmin,xmax = x.min(), x.max()
print("Minimum and Maximum values")
print(xmin,xmax)

[[0.22448268 0.37190556 0.44083883 0.98076847 0.47381481 0.76412462
  0.69111368 0.54169012 0.90132198 0.96306086]
 [0.00152125 0.26616212 0.45163166 0.62391559 0.43028014 0.58278047
  0.77332339 0.68553362 0.27890306 0.6390379 ]
 [0.01060606 0.72502237 0.25488995 0.29110062 0.54402301 0.18604386
  0.26039572 0.02581017 0.08887332 0.60161977]
 [0.94144498 0.35970463 0.56579652 0.95197159 0.82023286 0.37289782
  0.46803801 0.74612156 0.88807569 0.47827799]
 [0.95868093 0.50080778 0.79612058 0.4831296  0.46710548 0.05343815
  0.49864883 0.08785418 0.7225942  0.6107339 ]
 [0.43736657 0.43477367 0.83839331 0.27798424 0.51167835 0.62589655
  0.63930205 0.51298668 0.87911931 0.18886883]
 [0.40547425 0.67620038 0.39812979 0.66952109 0.82502282 0.21280102
  0.59851026 0.35848666 0.08586663 0.13039285]
 [0.81921178 0.00248894 0.91418791 0.47586971 0.79201733 0.20866395
  0.805266   0.30353797 0.17309123 0.05779425]
 [0.23659161 0.63472629 0.77644258 0.31078936 0.71972167 0.55939264
  0.79392273

#### 14. Create a random vector of size 30 and find the mean value (★☆☆) 
(**hint**: mean)

In [ ]:
z = np.random.random(30)
m = z.mean()
print(m)

0.5020460916816624


#### 15. Create a 2d array with 1 on the border and 0 inside (★☆☆) 
(**hint**: array\[1:-1, 1:-1\])

In [ ]:
Z = np.ones((10,10))
Z[1:-1,1:-1] = 0
print(Z)

[[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]]


#### 16. How to add a border (filled with 0's) around an existing array? (★☆☆) 
(**hint**: np.pad)

In [ ]:
z = np.ones((5,5))
z = np.pad(z,pad_width=1, mode='constant',constant_values=0)
print(z)

[[0. 0. 0. 0. 0. 0. 0.]
 [0. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 0.]
 [0. 0. 0. 0. 0. 0. 0.]]


#### 17. What is the result of the following expression? (★☆☆) 
(**hint**: NaN = not a number, inf = infinity)

```python
0 * np.nan
np.nan == np.nan
np.inf > np.nan
np.nan - np.nan
0.3 == 3 * 0.1
```

In [ ]:
print(0 * np.nan)
print(np.nan == np.nan)
print(np.inf > np.nan)
print(np.nan - np.nan)
print(0.3 == 3 * 0.1)

nan
False
False
nan
False


#### 18. Create a 5x5 matrix with values 1,2,3,4 just below the diagonal (★☆☆) 
(**hint**: np.diag)

In [ ]:
z = np.diag(1+np.arange(4),k=-1)
print(z)

[[0 0 0 0 0]
 [1 0 0 0 0]
 [0 2 0 0 0]
 [0 0 3 0 0]
 [0 0 0 4 0]]


#### 19. Create a 8x8 matrix and fill it with a checkerboard pattern (★☆☆) 
(**hint**: array\[::2\])

In [ ]:
Z = np.zeros((8,8),dtype=int)
Z[1::2,::2] = 1
Z[::2,1::2] = 1
print(Z)

[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]


#### 20. Consider a (6,7,8) shape array, what is the index (x,y,z) of the 100th element? 
(**hint**: np.unravel_index)

In [ ]:
print(np.unravel_index(100,(6,7,8)))

(1, 5, 4)


#### 21. Create a checkerboard 8x8 matrix using the tile function (★☆☆) 
(**hint**: np.tile)

In [ ]:
z = np.tile(np.array([[0,1],[1,0]]),(4,4))
print(z)

[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]


#### 22. Normalize a 5x5 random matrix (★☆☆) 
(**hint**: (x - min) / (max - min))

In [ ]:
x = np.random.random((5,5))
xmax,xmin=x.max(),x.min()
x = (x-xmin)/(xmax-xmin)
print(x)

[[0.51244144 0.69431798 0.65239061 0.77743732 0.        ]
 [0.90736514 0.54020502 0.68034853 0.80136196 0.22958009]
 [1.         0.74139755 0.24658782 0.93555787 0.97544672]
 [0.16513533 0.05549021 0.53517039 0.95233622 0.42460117]
 [0.64482181 0.19811326 0.71649651 0.5198283  0.6188658 ]]


#### 23. Create a custom dtype that describes a color as four unsigned bytes (RGBA) (★☆☆) 
(**hint**: np.dtype)

In [ ]:
RGBA = np.dtype([('red',np.uint8),('green',np.uint8),('blue',np.uint8),('alpha',np.uint8)])
color = np.array((1,2,4,3),dtype = RGBA)
print(color['red'])
type(color)

1


numpy.ndarray

#### 24. Multiply a 5x3 matrix by a 3x2 matrix (real matrix product) (★☆☆) 
(**hint**: np.dot | @)

In [ ]:
arr_1 = np.random.random((5,3)) 
arr_2 =np.random.random((3,2))
print(arr_1 @ arr_2)
np.dot(arr_1,arr_2)

[[0.66508756 0.85204093]
 [0.16309892 0.29751873]
 [0.59298627 0.84835468]
 [0.69951894 0.59074312]
 [0.26260471 0.41532315]]


array([[0.66508756, 0.85204093],
       [0.16309892, 0.29751873],
       [0.59298627, 0.84835468],
       [0.69951894, 0.59074312],
       [0.26260471, 0.41532315]])

#### 25. Given a 1D array, negate all elements which are between 3 and 8, in place. (★☆☆) 
(**hint**: >, <=)

In [ ]:
#arr = np.arange(16)
#print(arr>=3)
#arr[(arr>=3) & arr[(arr<=8)]*=(-1)
#print(arr)
arr =np.arange(16)

#### 26. What is the output of the following script? (★☆☆) 
(**hint**: np.sum)

```python
# Author: Jake VanderPlas

print(sum(range(5),-1))
from numpy import *
print(sum(range(5),-1))
```

In [ ]:
print(sum(range(5),-1))
from numpy import *
print(sum(range(5),-1))

10
10


#### 27. Consider an integer vector Z, which of these expressions are legal? (★☆☆)

```python
Z**Z
2 << Z >> 2
Z <- Z
1j*Z
Z/1/1
Z<Z>Z
```

In [ ]:
Z =arange(10)
Z<Z>Z

ValueError: ignored

#### 28. What are the result of the following expressions?

```python
np.array(0) / np.array(0)
np.array(0) // np.array(0)
np.array([np.nan]).astype(int).astype(float)
```

In [ ]:
np.array([np.nan]).astype(int).astype(float)

array([-9.22337204e+18])

#### 29. How to round away from zero a float array ? (★☆☆) 
(**hint**: np.uniform, np.copysign, np.ceil, np.abs)

In [ ]:
arr = np.random.random((5,5))
print(arr)
arr = np.round(arr,2)
print(arr)

[[0.32876638 0.36297801 0.24993146 0.53943937 0.6741232 ]
 [0.48561544 0.06082807 0.84772798 0.54156996 0.25172974]
 [0.50230808 0.64804698 0.58691213 0.39461941 0.46790529]
 [0.0295738  0.02137981 0.29701373 0.4643656  0.24309079]
 [0.9119612  0.66772273 0.60498202 0.87933904 0.65693888]]
[[0.33 0.36 0.25 0.54 0.67]
 [0.49 0.06 0.85 0.54 0.25]
 [0.5  0.65 0.59 0.39 0.47]
 [0.03 0.02 0.3  0.46 0.24]
 [0.91 0.67 0.6  0.88 0.66]]


#### 30. How to find common values between two arrays? (★☆☆) 
(**hint**: np.intersect1d)

In [ ]:
np.intersect1d

<function numpy.intersect1d(ar1, ar2, assume_unique=False, return_indices=False)>

#### 31. How to ignore all numpy warnings (not recommended)? (★☆☆) 
(**hint**: np.seterr, np.errstate)

In [ ]:
np.seterr(all="ignore")
np.errstate

numpy.errstate

#### 32. Is the following expressions true? (★☆☆) 
(**hint**: imaginary number)

```python
np.sqrt(-1) == np.emath.sqrt(-1)
```

In [ ]:
np.sqrt(-1) == np.emath.sqrt(-1)

False

#### 33. How to get the dates of yesterday, today and tomorrow? (★☆☆) 
(**hint**: np.datetime64, np.timedelta64)

In [ ]:
yesterday = np.datetime64('today', 'D') - np.timedelta64(1, 'D')
today     = np.datetime64('today', 'D')
tomorrow  = np.datetime64('today', 'D') + np.timedelta64(1, 'D')

#### 34. How to get all the dates corresponding to the month of July 2016? (★★☆) 
(**hint**: np.arange(dtype=datetime64\['D'\]))

In [ ]:
z = np.arange('2016-07','2016-08', dtype='datetime64[D]')
print(z)

['2016-07-01' '2016-07-02' '2016-07-03' '2016-07-04' '2016-07-05'
 '2016-07-06' '2016-07-07' '2016-07-08' '2016-07-09' '2016-07-10'
 '2016-07-11' '2016-07-12' '2016-07-13' '2016-07-14' '2016-07-15'
 '2016-07-16' '2016-07-17' '2016-07-18' '2016-07-19' '2016-07-20'
 '2016-07-21' '2016-07-22' '2016-07-23' '2016-07-24' '2016-07-25'
 '2016-07-26' '2016-07-27' '2016-07-28' '2016-07-29' '2016-07-30'
 '2016-07-31']


#### 35. How to compute ((A+B)\*(-A/2)) in place (without copy)? (★★☆) 
(**hint**: np.add(out=), np.negative(out=), np.multiply(out=), np.divide(out=))

In [3]:
import numpy as np
A = np.ones(3)*1
B = np.ones(3)*2
C = np.ones(3)*3
np.add(A,B,out=B)
np.divide(A,2,out=A)
np.negative(A,out=A)
np.dot(A,B)

-4.5

#### 36. Extract the integer part of a random array using 5 different methods (★★☆) 
(**hint**: %, np.floor, np.ceil, astype, np.trunc)

In [ ]:
Z = np.random.uniform(0,10,10)

print (Z - Z%1)
print (np.floor(Z))
print (np.ceil(Z)-1)
print (Z.astype(int))

[1. 7. 4. 5. 1. 4. 5. 9. 5. 3.]
[1. 7. 4. 5. 1. 4. 5. 9. 5. 3.]
[1. 7. 4. 5. 1. 4. 5. 9. 5. 3.]
[1 7 4 5 1 4 5 9 5 3]


#### 37. Create a 5x5 matrix with row values ranging from 0 to 4 (★★☆) 
(**hint**: np.arange)

In [ ]:
Z = np.zeros((5,5))
Z += np.arange(5)
print(Z)

[[0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]]


#### 38. Consider a generator function that generates 10 integers and use it to build an array (★☆☆) 
(**hint**: np.fromiter)

In [ ]:
def generate():
    for x in range(10):
        yield x
Z = np.fromiter(generate(),dtype=float,count=-1)
print(Z)

[0. 1. 2. 3. 4. 5. 6. 7. 8. 9.]


#### 39. Create a vector of size 10 with values ranging from 0 to 1, both excluded (★★☆) 
(**hint**: np.linspace)

In [ ]:
Z = np.linspace(0,1,11,endpoint=False)[1:]
print(Z)

[0.09090909 0.18181818 0.27272727 0.36363636 0.45454545 0.54545455
 0.63636364 0.72727273 0.81818182 0.90909091]


#### 40. Create a random vector of size 10 and sort it (★★☆) 
(**hint**: sort)

In [ ]:
Z = np.random.random(10)
Z.sort()
print(Z)

[0.14484206 0.18807892 0.18871238 0.19932692 0.27759957 0.60935492
 0.69364172 0.82040088 0.86343483 0.89640262]


#### 41. How to sum a small array faster than np.sum? (★★☆) 
(**hint**: np.add.reduce)

In [ ]:
z = np.arange(10)
np.add.reduce(z)

45

#### 42. Consider two random array A and B, check if they are equal (★★☆) 
(**hint**: np.allclose, np.array\_equal)

In [ ]:
a = np.random.randint(0,2,5)
b = np.random.randint(0,2,5)
equal = np.allclose(a,b)
print(equal)
np.array_equal(a,b)
print(equal)

False
False


#### 43. Make an array immutable (read-only) (★★☆) 
(**hint**: flags.writeable)

In [ ]:
z = np.zeros(10)
z.flags.writeable = False
z[0] =1

ValueError: ignored

#### 44. Consider a random 10x2 matrix representing cartesian coordinates, convert them to polar coordinates (★★☆) 
(**hint**: np.sqrt, np.arctan2)

In [ ]:
z=np.random.randint(0,9,(10,2))
x,y = z[:,0],z[:,1]
r = np.sqrt(x**2+y**2)
t = np.arctan2(y,x)
poles = np.c_[r,t]
print(poles)

[[ 6.40312424  0.89605538]
 [10.          0.92729522]
 [ 9.21954446  0.86217005]
 [ 1.          0.        ]
 [ 7.28010989  1.29249667]
 [ 1.          0.        ]
 [ 7.61577311  0.40489179]
 [ 5.09901951  0.19739556]
 [ 8.54400375  0.35877067]
 [ 5.          1.57079633]]


#### 45. Create random vector of size 10 and replace the maximum value by 0 (★★☆) 
(**hint**: argmax)

In [ ]:
arr = np.random.random(10)
print(arr)
arr[arr.argmax()]=0
print(arr)

[0.15854288 0.60651406 0.97108427 0.98662235 0.0514836  0.85793778
 0.65412054 0.94831269 0.09303742 0.55676319]
[0.15854288 0.60651406 0.97108427 0.         0.0514836  0.85793778
 0.65412054 0.94831269 0.09303742 0.55676319]


#### 46. Create a structured array with `x` and `y` coordinates covering the \[0,1\]x\[0,1\] area (★★☆) 
(**hint**: np.meshgrid)

In [ ]:
np.meshgrid

<function numpy.meshgrid(*xi, copy=True, sparse=False, indexing='xy')>

####  47. Given two arrays, X and Y, construct the Cauchy matrix C (Cij =1/(xi - yj)) 
(**hint**: np.subtract.outer)

In [ ]:
x = np.random.randint(0,11,10)
y = np.random.randint(0,11,10)
y = np.tile(y,(10,1))
x = np.tile(x,(10,1)).T
c= 1/(x-y)
c

array([[-0.33333333,         inf, -0.2       ,  0.25      ,  0.5       ,
        -0.2       , -0.33333333, -0.33333333,  0.5       , -0.2       ],
       [-0.25      , -1.        , -0.16666667,  0.33333333,  1.        ,
        -0.16666667, -0.25      , -0.25      ,  1.        , -0.16666667],
       [-0.2       , -0.5       , -0.14285714,  0.5       ,         inf,
        -0.14285714, -0.2       , -0.2       ,         inf, -0.14285714],
       [ 1.        ,  0.25      , -1.        ,  0.125     ,  0.16666667,
        -1.        ,  1.        ,  1.        ,  0.16666667, -1.        ],
       [ 1.        ,  0.25      , -1.        ,  0.125     ,  0.16666667,
        -1.        ,  1.        ,  1.        ,  0.16666667, -1.        ],
       [-0.33333333,         inf, -0.2       ,  0.25      ,  0.5       ,
        -0.2       , -0.33333333, -0.33333333,  0.5       , -0.2       ],
       [ 0.33333333,  0.16666667,  1.        ,  0.1       ,  0.125     ,
         1.        ,  0.33333333,  0.33333333

#### 48. Print the minimum and maximum representable value for each numpy scalar type (★★☆) 
(**hint**: np.iinfo, np.finfo, eps)

In [ ]:
for dtype in [np.int8, np.int32, np.int64]:
  print(np.iinfo(dtype).min)
  print(np.iinfo(dtype).max)
for dtype in [np.float32, np.float64]:
  print(np.finfo(dtype).min)
  print(np.finfo(dtype).max)
  print(np.finfo(dtype).eps)

-128
127
-2147483648
2147483647
-9223372036854775808
9223372036854775807
-3.4028235e+38
3.4028235e+38
1.1920929e-07
-1.7976931348623157e+308
1.7976931348623157e+308
2.220446049250313e-16


#### 49. How to print all the values of an array? (★★☆) 
(**hint**: np.set\_printoptions)

In [ ]:
#np.set_printoptions(threshold=np.nan)
z=[]
print(z)

[]


#### 50. How to find the closest value (to a given scalar) in a vector? (★★☆) 
(**hint**: argmin)

In [ ]:
arr = np.random.uniform(0,10,10)
scal = 5
arr_1 = np.abs(arr - 5)
ind = arr_1.argmin()
print(arr)
print('*'*60)
print(arr[ind])

[5.1465661  2.28035632 8.56510604 3.90622959 2.93834242 0.09976682
 7.16160688 9.49273286 9.35665741 6.42594327]
************************************************************
5.146566096090307


#### 51. Create a structured array representing a position (x,y) and a color (r,g,b) (★★☆) 
(**hint**: dtype)

In [5]:
z = np.zeros(10, [('position', [('x,',float,1),
                                ('y', float,1)]),
                  ('color',[('r', float,1),
                            ('g', float,1),
                            ('b', float,1)])])
print(z)

[((0., 0.), (0., 0., 0.)) ((0., 0.), (0., 0., 0.))
 ((0., 0.), (0., 0., 0.)) ((0., 0.), (0., 0., 0.))
 ((0., 0.), (0., 0., 0.)) ((0., 0.), (0., 0., 0.))
 ((0., 0.), (0., 0., 0.)) ((0., 0.), (0., 0., 0.))
 ((0., 0.), (0., 0., 0.)) ((0., 0.), (0., 0., 0.))]


/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:5: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  """


#### 52. Consider a random vector with shape (100,2) representing coordinates, find point by point distances (★★☆) 
(**hint**: np.atleast\_2d, T, np.sqrt)

In [7]:
z = np.random.random((10,2))
x,y = np.atleast_2d(z[:,0]),np.atleast_2d(z[:,1])
d = np.sqrt((x-x.T)**2+(y-y.T)**2)
print(d)

[[0.         0.11636011 1.01913942 0.35874986 0.8021401  0.68659034
  0.63603347 0.77245774 0.40595782 0.70546556]
 [0.11636011 0.         1.07223942 0.24823612 0.72786515 0.60250882
  0.62007906 0.8209432  0.40547956 0.73570548]
 [1.01913942 1.07223942 0.         1.13332975 1.02423874 1.06048835
  0.64276465 0.2526216  0.71243117 0.37349589]
 [0.35874986 0.24823612 1.13332975 0.         0.53292439 0.39289342
  0.56370648 0.88340806 0.420917   0.76583465]
 [0.8021401  0.72786515 1.02423874 0.53292439 0.         0.14519761
  0.40349517 0.83134585 0.52085768 0.68390831]
 [0.68659034 0.60250882 1.06048835 0.39289342 0.14519761 0.
  0.41832723 0.84496296 0.46599854 0.69917073]
 [0.63603347 0.62007906 0.64276465 0.56370648 0.40349517 0.41832723
  0.         0.43055378 0.23371692 0.28324733]
 [0.77245774 0.8209432  0.2526216  0.88340806 0.83134585 0.84496296
  0.43055378 0.         0.4628383  0.14753443]
 [0.40595782 0.40547956 0.71243117 0.420917   0.52085768 0.46599854
  0.23371692 0.46283

#### 53. How to convert a float (32 bits) array into an integer (32 bits) in place? 
(**hint**: astype(copy=False))

In [9]:
z = np.arange(10, dtype=np.int32)
z = z.astype(np.float32, copy= False)
print(z)

[0. 1. 2. 3. 4. 5. 6. 7. 8. 9.]


#### 54. How to read the following file? (★★☆) 
(**hint**: np.genfromtxt)

```
1, 2, 3, 4, 5
6,  ,  , 7, 8
 ,  , 9,10,11
```

In [11]:
from io import StringIO
s= StringIO('''1, 2, 3, 4, 5\n
    6,  ,  , 7, 8\n
    ,  , 9,10,11\n''')
z = np.genfromtxt(s, delimiter=",", dtype=np.int)
print(z)

[[ 1  2  3  4  5]
 [ 6 -1 -1  7  8]
 [-1 -1  9 10 11]]


/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:5: DeprecationWarning: `np.int` is a deprecated alias for the builtin `int`. To silence this warning, use `int` by itself. Doing this will not modify any behavior and is safe. When replacing `np.int`, you may wish to use e.g. `np.int64` or `np.int32` to specify the precision. If you wish to review your current use, check the release note link for additional information.
Deprecated in NumPy 1.20; for more details and guidance: https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations
  """


#### 55. What is the equivalent of enumerate for numpy arrays? (★★☆) 
(**hint**: np.ndenumerate, np.ndindex)

In [12]:
z = np.arange(9).reshape(3,3)
for index, value in np.ndenumerate(z):
  print(index,value)
for index in np.ndindex(z.shape):
  print(index, z[index])

(0, 0) 0
(0, 1) 1
(0, 2) 2
(1, 0) 3
(1, 1) 4
(1, 2) 5
(2, 0) 6
(2, 1) 7
(2, 2) 8
(0, 0) 0
(0, 1) 1
(0, 2) 2
(1, 0) 3
(1, 1) 4
(1, 2) 5
(2, 0) 6
(2, 1) 7
(2, 2) 8


#### 56. Generate a generic 2D Gaussian-like array (★★☆) 
(**hint**: np.meshgrid, np.exp)

In [13]:
x,y = np.meshgrid(np.linspace(-1,1,10), np.linspace(-1,1,10))
d = np.sqrt(x*x*+y*y)
sigma, mu = 1.0,0.0
g = np.exp(-(d-mu)**2/(2.0*sigma**2))
print(g)

[[0.60653066 0.7389913  0.85699689 0.94595947 0.99384617 0.99384617
  0.94595947 0.85699689 0.7389913  0.60653066]
 [0.7389913  0.83278885 0.91087038 0.96695078 0.99627278 0.99627278
  0.96695078 0.91087038 0.83278885 0.7389913 ]
 [0.85699689 0.91087038 0.95348657 0.98299939 0.99809662 0.99809662
  0.98299939 0.95348657 0.91087038 0.85699689]
 [0.94595947 0.96695078 0.98299939 0.99384617 0.99931436 0.99931436
  0.99384617 0.98299939 0.96695078 0.94595947]
 [0.99384617 0.99627278 0.99809662 0.99931436 0.9999238  0.9999238
  0.99931436 0.99809662 0.99627278 0.99384617]
 [0.99384617 0.99627278 0.99809662 0.99931436 0.9999238  0.9999238
  0.99931436 0.99809662 0.99627278 0.99384617]
 [0.94595947 0.96695078 0.98299939 0.99384617 0.99931436 0.99931436
  0.99384617 0.98299939 0.96695078 0.94595947]
 [0.85699689 0.91087038 0.95348657 0.98299939 0.99809662 0.99809662
  0.98299939 0.95348657 0.91087038 0.85699689]
 [0.7389913  0.83278885 0.91087038 0.96695078 0.99627278 0.99627278
  0.96695078 0

#### 57. How to randomly place p elements in a 2D array? (★★☆) 
(**hint**: np.put, np.random.choice)

In [14]:
n = 10 
p =3
z= np.zeros((n,n))
np.put(z,np.random.choice(range(n*n),p,replace=False),1)
print(z)

[[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 1. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]]


#### 58. Subtract the mean of each row of a matrix (★★☆) 
(**hint**: mean(axis=,keepdims=))

In [16]:
x = np.random.rand(5,10)
y = x-x.mean(axis=1, keepdims=True)
y

array([[ 0.37434772,  0.13106745,  0.10396461, -0.41331707, -0.47070562,
         0.27926128, -0.39740433,  0.35889212, -0.12309292,  0.15698677],
       [-0.42818333,  0.08834747,  0.33570808, -0.47195662, -0.10919765,
        -0.06708559,  0.19390222,  0.40325072,  0.30306975, -0.24785503],
       [-0.24272828,  0.13341278,  0.24807031,  0.21022029, -0.11788861,
         0.1647403 , -0.0741893 ,  0.15687199, -0.43178378, -0.0467257 ],
       [-0.49024882,  0.21101369, -0.20836805,  0.10217648, -0.04739377,
         0.25261542,  0.34168031,  0.1795052 , -0.38249242,  0.04151196],
       [ 0.34089609,  0.05526406,  0.31723863, -0.35994366,  0.32004514,
        -0.09029697,  0.20925964, -0.20773337, -0.47230243, -0.11242713]])

#### 59. How to sort an array by the nth column? (★★☆) 
(**hint**: argsort)

In [18]:
z = np.random.randint(0,10,(5,5))
print(z)
print(z[(-z)[:,1].argsort()])
print(z[:,z[1,:].argsort()])

[[2 0 6 2 1]
 [3 4 6 2 8]
 [9 8 7 5 3]
 [9 9 1 8 8]
 [4 1 9 6 8]]
[[9 9 1 8 8]
 [9 8 7 5 3]
 [3 4 6 2 8]
 [4 1 9 6 8]
 [2 0 6 2 1]]
[[2 2 0 6 1]
 [2 3 4 6 8]
 [5 9 8 7 3]
 [8 9 9 1 8]
 [6 4 1 9 8]]


#### 60. How to tell if a given 2D array has null columns? (★★☆) 
(**hint**: any, ~)

In [19]:
z = np.random.randint(0,3,(3,10))
z[:,1]=0
z=z.astype(bool)
print(z)
print(~z)
(z).any(axis=0)

[[ True False  True  True  True  True  True  True False  True]
 [False False  True  True False  True  True  True  True  True]
 [ True False False False False  True  True  True  True  True]]
[[False  True False False False False False False  True False]
 [ True  True False False  True False False False False False]
 [False  True  True  True  True False False False False False]]


array([ True, False,  True,  True,  True,  True,  True,  True,  True,
        True])

#### 61. Find the nearest value from a given value in an array (★★☆) 
(**hint**: np.abs, argmin, flat)

In [22]:
Z = np.random.uniform(0,1,10)
z = 0.5
m = Z.flat[np.abs(Z - z).argmin()]
print(m)

0.5965033483792513


#### 62. Considering two arrays with shape (1,3) and (3,1), how to compute their sum using an iterator? (★★☆) 
(**hint**: np.nditer)

In [27]:
A = np.arange(3).reshape(3,1)
B = np.arange(3).reshape(1,3)
it = np.nditer([A,B,None])
for x,y,z in it: z[...] = x + y
print(it.operands[2])

[[0 1 2]
 [1 2 3]
 [2 3 4]]


#### 63. Create an array class that has a name attribute (★★☆) 
(**hint**: class method)

In [28]:
class NamedArray(np.ndarray):
    def __new__(cls, array, name="no name"):
        obj = np.asarray(array).view(cls)
        obj.name = name
        return obj
    def __array_finalize__(self, obj):
        if obj is None: return
        self.info = getattr(obj, 'name', "no name")

Z = NamedArray(np.arange(10), "range_10")
print (Z.name)

range_10


#### 64. Consider a given vector, how to add 1 to each element indexed by a second vector (be careful with repeated indices)? (★★★) 
(**hint**: np.bincount | np.add.at)

In [30]:
z = np.ones(10)
i = np.random.randint(0,len(z),20)
z+=np.bincount(i, minlength=len(z))
print(z)

[2. 4. 3. 4. 2. 7. 2. 1. 1. 4.]


#### 65. How to accumulate elements of a vector (X) to an array (F) based on an index list (I)? (★★★) 
(**hint**: np.bincount)

In [32]:
x = [1,2,3,4,5,6]
i = [1,3,9,3,4,1]
f = np.bincount(i,x)
print(f)

[0. 7. 0. 6. 5. 0. 0. 0. 0. 3.]


#### 66. Considering a (w,h,3) image of (dtype=ubyte), compute the number of unique colors (★★★) 
(**hint**: np.unique)

In [37]:
w,h = 16,16
I = np.random.randint(0,2,(h,w,3)).astype(np.ubyte)
F = I[...,0]*256*256 + I[...,1]*256 +I[...,2]
n = len(np.unique(F))
print(np.unique(I))

[0 1]


#### 67. Considering a four dimensions array, how to get sum over the last two axis at once? (★★★) 
(**hint**: sum(axis=(-2,-1)))

In [41]:
a = np.random.randint(0,10,(3,4,3,4))
sum = a.reshape(a.shape[:-2]+(-1,)).sum(axis=-1)
print(sum)

[[56 56 70 59]
 [52 56 45 61]
 [64 48 54 48]]


#### 68. Considering a one-dimensional vector D, how to compute means of subsets of D using a vector S of same size describing subset  indices? (★★★) 
(**hint**: np.bincount)

In [42]:
d = np.random.uniform(0,1,100)
s = np.random.randint(0,10,100)
d_sums = np.bincount(s, weights=d)
d_counts = np.bincount(s)
d_means = d_sums/d_counts
print(d_means)

[0.69149943 0.5718169  0.6020339  0.58548654 0.44584049 0.41441821
 0.40984899 0.56067746 0.53267726 0.42904342]


#### 69. How to get the diagonal of a dot product? (★★★) 
(**hint**: np.diag)

In [43]:
a = np.random.randint(0,10,(3,3))
b = np.random.randint(0,10,(3,3))
np.diag(np.dot(a,b))

array([45, 15, 75])

#### 70. Consider the vector \[1, 2, 3, 4, 5\], how to build a new vector with 3 consecutive zeros interleaved between each value? (★★★) 
(**hint**: array\[::4\])

In [44]:
z = np.array([1,2,3,4,5])
nz = 3
z0 = np.zeros(len(z)+(len(z)-1)*(nz))
z0[::nz+1]=z
print(z0)

[1. 0. 0. 0. 2. 0. 0. 0. 3. 0. 0. 0. 4. 0. 0. 0. 5.]


#### 71. Consider an array of dimension (5,5,3), how to mulitply it by an array with dimensions (5,5)? (★★★) 
(**hint**: array\[:, :, None\])

In [45]:
a = np.ones((5,5,3))
b = 2*np.ones((5,5))
print(a*b[:,:,None])

[[[2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]]

 [[2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]]

 [[2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]]

 [[2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]]

 [[2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]]]


#### 72. How to swap two rows of an array? (★★★) 
(**hint**: array\[\[\]\] = array\[\[\]\])

In [47]:
a = np.arange(25).reshape(5,5)
a[[0,1]] = a[[1,0]]
print(a)

[[ 5  6  7  8  9]
 [ 0  1  2  3  4]
 [10 11 12 13 14]
 [15 16 17 18 19]
 [20 21 22 23 24]]


#### 73. Consider a set of 10 triplets describing 10 triangles (with shared vertices), find the set of unique line segments composing all the  triangles (★★★) 
(**hint**: repeat, np.roll, np.sort, view, np.unique)

#### 74. Given an array C that is a bincount, how to produce an array A such that np.bincount(A) == C? (★★★) 
(**hint**: np.repeat)

In [48]:
c = np.bincount([1,1,2,3,4,4,6])
a = np.repeat(np.arange(len(c)),c)
print(a)

[1 1 2 3 4 4 6]


#### 75. How to compute averages using a sliding window over an array? (★★★) 
(**hint**: np.cumsum)

In [51]:
def moving_average(a, n=3):
  ret = np.cumsum(a, dtype=float)
  ret[n:] = ret[n:]-ret[:-n]
  return ret[n-1:]/n
z=np.arange(20)
print(moving_average(z,n=3))

[ 1.  2.  3.  4.  5.  6.  7.  8.  9. 10. 11. 12. 13. 14. 15. 16. 17. 18.]


#### 76. Consider a one-dimensional array Z, build a two-dimensional array whose first row is (Z\[0\],Z\[1\],Z\[2\]) and each subsequent row is  shifted by 1 (last row should be (Z\[-3\],Z\[-2\],Z\[-1\]) (★★★) 
(**hint**: from numpy.lib import stride_tricks)

In [52]:
def rolling(a,window):
  shape = (a.size-window+1,window)
  strides = (a.itemsize, a.itemsize)
  return np.lib.stride_tricks.as_strided(a, shape=shape, strides=strides)
z= rolling(np.arange(10),3)
print(z)

[[0 1 2]
 [1 2 3]
 [2 3 4]
 [3 4 5]
 [4 5 6]
 [5 6 7]
 [6 7 8]
 [7 8 9]]


#### 77. How to negate a boolean, or to change the sign of a float inplace? (★★★) 
(**hint**: np.logical_not, np.negative)

In [53]:
z = np.random.randint(0,2,100)
print("original")
print(z)
print("Negating a boolean : ")
print(np.logical_not(z, out=z))

z = np.random.uniform(-1.0,1.0,10)
print("original")
print(z)
print("change the sign of float inplace : ")
print(np.negative(z, out=z))

original
[1 0 1 1 0 1 0 0 1 0 1 0 1 0 1 0 0 0 1 0 1 0 0 1 1 0 1 1 1 1 0 0 1 1 0 1 1
 1 0 0 0 1 0 1 1 0 1 0 1 0 1 1 0 1 1 1 1 0 0 0 0 1 0 0 0 0 0 1 0 0 0 1 1 1
 0 0 1 1 1 1 0 1 0 1 0 1 0 1 0 0 0 0 1 1 0 0 1 1 0 0]
Negating a boolean : 
[0 1 0 0 1 0 1 1 0 1 0 1 0 1 0 1 1 1 0 1 0 1 1 0 0 1 0 0 0 0 1 1 0 0 1 0 0
 0 1 1 1 0 1 0 0 1 0 1 0 1 0 0 1 0 0 0 0 1 1 1 1 0 1 1 1 1 1 0 1 1 1 0 0 0
 1 1 0 0 0 0 1 0 1 0 1 0 1 0 1 1 1 1 0 0 1 1 0 0 1 1]
original
[-0.38083723 -0.14946994  0.11705514 -0.19160363 -0.17933351 -0.47288294
  0.33778989  0.65885972 -0.53583982  0.02726186]
change the sign of float inplace : 
[ 0.38083723  0.14946994 -0.11705514  0.19160363  0.17933351  0.47288294
 -0.33778989 -0.65885972  0.53583982 -0.02726186]


#### 78. Consider 2 sets of points P0,P1 describing lines (2d) and a point p, how to compute distance from p to each line i  (P0\[i\],P1\[i\])? (★★★)

#### 79. Consider 2 sets of points P0,P1 describing lines (2d) and a set of points P, how to compute distance from each point j (P\[j\]) to each line i (P0\[i\],P1\[i\])? (★★★)

#### 80. Consider an arbitrary array, write a function that extract a subpart with a fixed shape and centered on a given element (pad with a `fill` value when necessary) (★★★) 
(**hint**: minimum, maximum)

#### 81. Consider an array Z = \[1,2,3,4,5,6,7,8,9,10,11,12,13,14\], how to generate an array R = \[\[1,2,3,4\], \[2,3,4,5\], \[3,4,5,6\], ..., \[11,12,13,14\]\]? (★★★) 
(**hint**: stride\_tricks.as\_strided)

#### 82. Compute a matrix rank (★★★) 
(**hint**: np.linalg.svd) (suggestion: np.linalg.svd)

In [54]:
z = np.random.uniform(0,1,(10,10))
u,s, v= np.linalg.svd(z)
rank = np.sum(s>1e-10)
print(rank)

10


#### 83. How to find the most frequent value in an array? 
(**hint**: np.bincount, argmax)

In [56]:
z = np.random.randint(0,10,50)
print(z)
print('rank: ', np.bincount(z).argmax())

[0 2 3 7 7 5 0 6 8 7 2 8 5 4 1 4 9 2 5 5 0 9 4 5 9 5 5 3 4 7 8 6 5 6 3 3 6
 1 0 8 2 8 5 7 2 8 4 8 1 1]
rank:  5


#### 84. Extract all the contiguous 3x3 blocks from a random 10x10 matrix (★★★) 
(**hint**: stride\_tricks.as\_strided)

In [58]:
Z = np.random.randint(0,5,(10,10))
n = 3
i = 1 + (Z.shape[0]-3)
j = 1 + (Z.shape[1]-3)
C = stride_tricks.as_strided(Z, shape=(i, j, n, n), strides=Z.strides + Z.strides)
print(C)

NameError: ignored

#### 85. Create a 2D array subclass such that Z\[i,j\] == Z\[j,i\] (★★★) 
(**hint**: class method)

#### 86. Consider a set of p matrices wich shape (n,n) and a set of p vectors with shape (n,1). How to compute the sum of of the p matrix products at once? (result has shape (n,1)) (★★★) 
(**hint**: np.tensordot)

In [59]:
p,n = 10,20
m = np.ones((p,n,n))
v = np.ones((p,n,1))
s = np.tensordot(m,v, axes=[[0,2],[0,1]])
print(s)

[[200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]]


#### 87. Consider a 16x16 array, how to get the block-sum (block size is 4x4)? (★★★) 
(**hint**: np.add.reduceat)

In [60]:
z = np.ones((16,16))
k=4
s=np.add.reduceat(np.add.reduceat(z, np.arange(0, z.shape[0],k), axis=0),
                  np.arange(0,z.shape[1],k),axis=1)
print('input array')
print(z)
print('block sum')
print(s)

input array
[[1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]]
block sum
[[16. 16. 16. 16.]
 [16. 16. 16. 16.]
 [16. 16. 16. 16.]
 [16. 16. 16. 16.]]


#### 88. How to implement the Game of Life using numpy arrays? (★★★)

#### 89. How to get the n largest values of an array (★★★) 
(**hint**: np.argsort | np.argpartition)

#### 90. Given an arbitrary number of vectors, build the cartesian product (every combinations of every item) (★★★) 
(**hint**: np.indices)

In [63]:
def cartesian(arrays):
  arrays = [np.asarray(a) for a in arrays]
  shape = (len(x) for x in arrays)

  ix = np.indices(shape, dtype=int)
  ix = ix.reshape(len(arrays), -1).T
  for n, arr in enumerate(arrays):
    ix[:,n] = arrays[n][ix[:,n]]
  return ix
print(cartesian(([1,2,3],[4,5],[6,7])))

[[1 4 6]
 [1 4 7]
 [1 5 6]
 [1 5 7]
 [2 4 6]
 [2 4 7]
 [2 5 6]
 [2 5 7]
 [3 4 6]
 [3 4 7]
 [3 5 6]
 [3 5 7]]


#### 91. How to create a record array from a regular array? (★★★) 
(**hint**: np.core.records.fromarrays)

In [68]:
z = np.array([("hello",2.5,3),
              ("world", 3.6,2)])
r = np.core.records.fromarrays(z.T,
                               names ='col1,col2,col3',
                               formats = 'S8,f8,i8')
print(r)

[(b'hello', 2.5, 3) (b'world', 3.6, 2)]


#### 92. Consider a large vector Z, compute Z to the power of 3 using 3 different methods (★★★) 
(**hint**: np.power, \*, np.einsum)

#### 93. Consider two arrays A and B of shape (8,3) and (2,2). How to find rows of A that contain elements of each row of B regardless of the order of the elements in B? (★★★) 
(**hint**: np.where)

In [75]:
a = np.random.randint(0,5,(8,3))
b = np.random.randint(0,5,(2,2))
c = (a[..., np.newaxis, np.newaxis]==b)
rows = (c.sum(axis=(1,2,3)) >=b.shape[1]).nonzero()[0]
print(rows)

[0 1 2 3 4 5 6 7]


#### 94. Considering a 10x3 matrix, extract rows with unequal values (e.g. \[2,2,3\]) (★★★)

In [76]:
z = np.random.randint(0,5,(10,3))
e = np.logical_and.reduce(z[:,1:]==z[:,:-1],axis=1)
u = z[~e]
print(z)
print(u)

[[4 1 2]
 [3 0 4]
 [4 2 4]
 [3 0 0]
 [4 2 1]
 [2 3 0]
 [1 3 0]
 [4 1 0]
 [4 0 1]
 [4 4 0]]
[[4 1 2]
 [3 0 4]
 [4 2 4]
 [3 0 0]
 [4 2 1]
 [2 3 0]
 [1 3 0]
 [4 1 0]
 [4 0 1]
 [4 4 0]]


#### 95. Convert a vector of ints into a matrix binary representation (★★★) 
(**hint**: np.unpackbits)

In [78]:
i = np.array([0,1,2,3,15,16,32,64,128], dtype=np.uint8)
print(np.unpackbits(i[:, np.newaxis],axis=1))

[[0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 1]
 [0 0 0 0 0 0 1 0]
 [0 0 0 0 0 0 1 1]
 [0 0 0 0 1 1 1 1]
 [0 0 0 1 0 0 0 0]
 [0 0 1 0 0 0 0 0]
 [0 1 0 0 0 0 0 0]
 [1 0 0 0 0 0 0 0]]


#### 96. Given a two dimensional array, how to extract unique rows? (★★★) 
(**hint**: np.ascontiguousarray)

#### 97. Considering 2 vectors A & B, write the einsum equivalent of inner, outer, sum, and mul function (★★★) 
(**hint**: np.einsum)

#### 98. Considering a path described by two vectors (X,Y), how to sample it using equidistant samples (★★★)? 
(**hint**: np.cumsum, np.interp)

#### 99. Given an integer n and a 2D array X, select from X the rows which can be interpreted as draws from a multinomial distribution with n degrees, i.e., the rows which only contain integers and which sum to n. (★★★) 
(**hint**: np.logical\_and.reduce, np.mod)

#### 100. Compute bootstrapped 95% confidence intervals for the mean of a 1D array X (i.e., resample the elements of an array with replacement N times, compute the mean of each sample, and then compute percentiles over the means). (★★★) 
(**hint**: np.percentile)